name:                concurrent-resource-map
version:             0.1.0.0
github:              "Fuuzetsu/concurrent-resource-map"
license:             BSD3
author:              "Mateusz Kowalczyk"
maintainer:          "fuuzetsu@fuuzetsu.co.uk"
copyright:           "2020 Mateusz Kowalczyk"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            Concurrent resource map
category:            Data

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Fuuzetsu/concurrent-resource-map#readme>
tested-with: GHC ==8.10.1 || ==8.8.3 || ==8.6.3 || ==8.4.4 || ==8.2.2 || ==8.0.2 || ==7.10.3

dependencies:
- base >= 4.8 && < 5

library:
  source-dirs: src
  ghc-options:
    - -O2
  dependencies:
    - base
    - containers

tests:
  concurrent-resource-map-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - concurrent-resource-map
    - random
    - stm
